spring.application.name=ExamSimulation

# Activar perfil (opcional)
spring.profiles.active=db-h2

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:ExamPractice;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver



# Consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Pool opcional (puede omitirse para H2 simple)
spring.datasource.hikari.maximum-pool-size=50

# Ejecutar schema.sql al inicio
spring.sql.init.mode=always
